python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=64 --n_head=12 --n_embd=768 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=32 --n_head=12 --n_embd=768 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=16 --n_head=12 --n_embd=768 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=8 --n_head=12 --n_embd=768 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=4 --n_head=12 --n_embd=768 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=64 --n_head=16 --n_embd=1024 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=32 --n_head=16 --n_embd=1024 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=16 --n_head=16 --n_embd=1024 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=8 --n_head=16 --n_embd=1024 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=4 --n_head=16 --n_embd=1024 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=64 --n_head=32 --n_embd=2048 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=32 --n_head=32 --n_embd=2048 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=16 --n_head=32 --n_embd=2048 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=8 --n_head=32 --n_embd=2048 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=4 --n_head=32 --n_embd=2048 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=64 --n_head=32 --n_embd=2560 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=32 --n_head=32 --n_embd=2560 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=16 --n_head=32 --n_embd=2560 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=8 --n_head=32 --n_embd=2560 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=4 --n_head=32 --n_embd=2560 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=32 --n_head=32 --n_embd=4096 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=16 --n_head=32 --n_embd=4096 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=8 --n_head=32 --n_embd=4096 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=4 --n_head=32 --n_embd=4096 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=32 --n_head=40 --n_embd=5120 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=16 --n_head=40 --n_embd=5120 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=8 --n_head=40 --n_embd=5120 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=4 --n_head=40 --n_embd=5120 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=16 --n_head=56 --n_embd=7168 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=8 --n_head=56 --n_embd=7168 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=4 --n_head=56 --n_embd=7168 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=4 --n_head=72 --n_embd=9216 --n_layer=1 --block_size=1024
python train.py config/train_gpt2.py --compile=False --wandb_log=False --dataset=shakespeare_char --batch_size=1 --n_head=96 --n_embd=12288 --n_layer=1 --block_size=1024
